### ISSUE TITLE
Call to metrics.Configure and sim.StartSimulation aren't awaited

### ISSUE THREAD

**Issue by sergeybykov** [OrleansContrib/Orleans.TelemetryConsumers.MetricsTracker#7]
Call to `metrics.Configure` on https://github.com/OrleansContrib/Orleans.TelemetryConsumers.MetricsTracker/blob/master/MetricsTracker.TestHost/Program.cs#L45 and to `sim.StartSimulation` on https://github.com/OrleansContrib/Orleans.TelemetryConsumers.MetricsTracker/blob/master/MetricsTracker.TestHost/Program.cs#L60 aren't awaited. So they can silently fail, and the rest of the code won't work. I think it is better to explicitly fail 'Main` if either of those calls fails or maybe retry them.

**Comment by danvanderboom** [comment]
Good catch. I'll take care of it. 

Thanks!

**Comment by danvanderboom** [comment]
Done.
